### ISSUE TITLE
shaking and shivering too much, and why?

### ISSUE THREAD

**Issue by Guanbin-Huang** [siddhanthaldar/BAKU#1]
hi, thank you for your great contribution to multi task policy learning.
any suggestion for improvement on shaking and shivering especially for long horizonal task.
this one
https://baku-robot.github.io/#:~:text=BAKU%20on%20Long%20Horizon%20Tasks

**Comment by siddhanthaldar** [comment]
Hi,

Increasing the policy frequency should fix the vibrations. You can make the change [here](https://github.com/siddhanthaldar/Open-Teach/blob/a6063fff67bb9beec27905529f3fd6ebd6ddfab2/openteach/constants.py#L95) if you are using an xArm robot.

Hope that answers your question.

**Comment by Holmes-GU** [comment]
> hi, thank you for your great contribution to multi task policy learning. any suggestion for improvement on shaking and shivering especially for long horizonal task. this one https://baku-robot.github.io/#:~:text=BAKU%20on%20Long%20Horizon%20Tasks

Hi,
Have you successfully trained the BAKU?
